// Single-page Ref Doc — the one-pager content rendered for the brand and
// laid out to fit on a single printed page (A4 / US Letter). Linked from
// the landing pages alongside "watch / launch demo / git repo". The same
// page is captured to PDF by scripts/build_pdf.sh and served at
// /scout-room-ref-doc.pdf so external links never break.
//
// The print styles below collapse the nav and hide hover effects so a
// browser "Save as PDF" produces the same artifact as the headless capture.

export const metadata = { title: "Ref Doc — The Scout Room" };

const ARCH_ROWS = [
  { layer: "Sources",    tech: "Lahman · Statcast · MLB Stats API",        note: "150 years · pitch-level · live" },
  { layer: "Ingestion",  tech: "Fivetran custom + HTTP connectors",         note: "Schedule, retry, schema drift" },
  { layer: "Storage",    tech: "Apache Iceberg on S3",                      note: "ACID, time travel, open format" },
  { layer: "Transform",  tech: "dbt · bronze → silver → gold",               note: "10+ models, tests, docs" },
  { layer: "Compute",    tech: "Snowflake (federates Iceberg directly)",     note: "External volumes, no copies" },
  { layer: "AI surface", tech: "Cortex EMBED · COSINE · SEARCH · COMPLETE · ANALYST", note: "Vectors, comp, narrative, NL Q+A" },
  { layer: "Viewer",     tech: "Next.js 14 · static export",                note: "Bundled fixture, offline-safe" },
];

const VALUE_ROWS = [
  { who: "Baseball fan",        gets: "A one-of-one scout report about their hometown and team" },
  { who: "Sales engineer",      gets: "A working app that exercises every ODI layer in five minutes" },
  { who: "Data-platform buyer", gets: "Iceberg as system of record, Snowflake as one of N compute engines" },
  { who: "Data engineer",       gets: "Source code for every panel — dbt models, Cortex SQL, scout engine in TypeScript" },
  { who: "Executive sponsor",   gets: "One repo, a few hundred lines of dbt, a Next.js viewer that ships in a sprint" },
];

export default function RefDocPage() {
  return (
    <main className="ref-doc-root">
      <article className="ref-doc">
        {/* Header */}
        <header className="ref-doc-header">
          <div className="ref-doc-eyebrow">Fivetran ODI Demo · Reference Doc</div>
          <h1 className="ref-doc-title">
            The Scout Room<span className="ref-doc-dot">.</span>
          </h1>
          <p className="ref-doc-lede">
            A fan types their hometown. Snowflake builds them a personalized scout report from
            150 years of MLB data. Every section is computed from gold tables Fivetran moved,
            dbt shaped, and Cortex narrated. No two reports are the same.
          </p>
        </header>

        {/* Hook + value */}
        <section className="ref-doc-section">
          <h2 className="ref-doc-h2">What the demo does</h2>
          <p className="ref-doc-p">
            One input — a city and state — produces a five-section report: hometown heroes within
            75 miles, a prospect persona for the inferred franchise, a hidden comp built on
            era-adjusted z-scores, a Did-You-Know panel with a US-state choropleth, and a closing
            paragraph generated by Cortex. Every chart carries a sentence that reads off its own
            numbers, not a template.
          </p>
        </section>

        {/* Architecture */}
        <section className="ref-doc-section">
          <h2 className="ref-doc-h2">Architecture in one table</h2>
          <table className="ref-doc-table">
            <thead>
              <tr>
                <th>Layer</th>
                <th>Tech</th>
                <th>What it does here</th>
              </tr>
            </thead>
            <tbody>
              {ARCH_ROWS.map((r) => (
                <tr key={r.layer}>
                  <td className="ref-doc-layer">{r.layer}</td>
                  <td className="ref-doc-tech">{r.tech}</td>
                  <td>{r.note}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </section>

        {/* Audience cuts */}
        <section className="ref-doc-section">
          <h2 className="ref-doc-h2">Who this demo serves</h2>
          <table className="ref-doc-table">
            <thead>
              <tr>
                <th>Audience</th>
                <th>What they get</th>
              </tr>
            </thead>
            <tbody>
              {VALUE_ROWS.map((r) => (
                <tr key={r.who}>
                  <td className="ref-doc-layer">{r.who}</td>
                  <td>{r.gets}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </section>

        {/* Why ODI */}
        <section className="ref-doc-section">
          <h2 className="ref-doc-h2">Why ODI is the story</h2>
          <p className="ref-doc-p">
            Open table format underneath (Iceberg on S3) means the prospect&apos;s data is portable.
            Snowflake is one of N engines that can query the same bytes. dbt promotes through three
            layers without ever exporting the lake. Cortex layers vectors, search, and an LLM on top
            of the warehouse the prospect already knows. What you see in this demo would have been
            a multi-quarter platform project a year ago. With ODI it ships in a sprint.
          </p>
        </section>

        {/* Footer with links */}
        <footer className="ref-doc-footer">
          <div className="ref-doc-foot-row">
            <span className="ref-doc-foot-label">Live demo</span>
            <span className="ref-doc-foot-value">scout-room.fivetran.com</span>
          </div>
          <div className="ref-doc-foot-row">
            <span className="ref-doc-foot-label">Source</span>
            <span className="ref-doc-foot-value">github.com/fivetran-jasonchletsos/the-scout-room</span>
          </div>
          <div className="ref-doc-foot-row">
            <span className="ref-doc-foot-label">Data</span>
            <span className="ref-doc-foot-value">Sean Lahman Baseball DB (CC BY-SA 3.0) · MLB Statcast · MLB Stats API</span>
          </div>
        </footer>
      </article>
    </main>
  );
}
